//! # Git advisor — the model half of the F-09 git manager
//!
//! The git manager's own invariants stand: branch names come from UUIDs
//! (GIT-04) and attribution lives in the ledger, not in commit text
//! (GIT-03). What the model contributes here is bounded to two things:
//!
//! - **commit detail**: a short body appended under a subject line that is
//!   still generated by [`crate::supervisor`], never replacing it;
//! - **rebase advice**: a *choice* between rebasing onto a validated commit
//!   and escalating to a human, never the argv that runs it.
//!
//! Everything the model returns is sanitized before use, and every failure
//! path — no advisor configured, provider error, timeout, unparseable
//! answer — degrades to exactly the deterministic behavior that existed
//! before this module. A commit never fails because a model was slow.

use std::sync::Arc;
use std::time::Duration;

use agentos_adapters::{AdapterEvent, RuntimeAdapter, SpawnSpec};
use tokio::sync::broadcast::error::RecvError;
use uuid::Uuid;

/// The `agent_role` whose registry record configures the advisor. No
/// record (and no static role mapping) means no advisor: the git manager
/// runs exactly as it did before.
pub const GIT_ADVISOR_ROLE: &str = "git-manager";

/// Longest commit body accepted from the model, in lines and in bytes.
const MAX_DETAIL_LINES: usize = 5;
const MAX_DETAIL_BYTES: usize = 400;

/// What the model is told about a pending commit. Facts only — every field
/// is harness-derived, none of it is model text coming back around.
#[derive(Debug, Clone)]
pub struct CommitFacts {
    /// Workflow node that produced the change.
    pub node_id: String,
    /// Run the audit bundle belongs to.
    pub run_id: String,
    /// Generated branch (`agentos/<run8>/<task8>`).
    pub branch: String,
    /// Repo-relative paths `git status --porcelain` reported.
    pub files: Vec<String>,
}

/// What the model is told about a rejected, stale-base mutation.
#[derive(Debug, Clone)]
pub struct StaleBaseFacts {
    /// Node whose mutation was rejected.
    pub node_id: String,
    /// Base commit the request was built against.
    pub base_commit: String,
    /// Where the branch actually is now.
    pub head_commit: String,
    /// Paths that moved under the request since it was queued.
    pub files: Vec<String>,
}

/// The advisor's answer for a stale base. Deliberately two-valued: there is
/// no variant that carries a command.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RebaseAdvice {
    /// Replay the branch onto this commit. The sha is syntactically
    /// validated here and must still be resolved by `git rev-parse` at the
    /// call site before it reaches the CLI.
    Rebase { onto: String },
    /// Hand it to a human, with the model's reason for the record.
    Escalate { reason: String },
}

/// One-shot model access for the git manager.
pub struct GitAdvisor {
    adapter: Arc<dyn RuntimeAdapter>,
    model: Option<String>,
    timeout: Duration,
}

impl GitAdvisor {
    /// Bind an advisor to a runtime. `model` is the registry record's slug
    /// (`gemini-3.1-pro-high` for the seeded agy record); `None` takes the
    /// adapter default.
    pub fn new(adapter: Arc<dyn RuntimeAdapter>, model: Option<String>, timeout: Duration) -> Self {
        Self {
            adapter,
            model,
            timeout,
        }
    }

    /// A short body for the commit under the deterministic subject, or
    /// `None` if the model was unavailable, slow, or said nothing usable.
    pub async fn commit_detail(&self, facts: &CommitFacts) -> Option<String> {
        let prompt = format!(
            "You are the git manager for an agent harness. Describe, for a human reading \
             `git log`, what this commit contains. Facts:\n\
             - node: {node}\n\
             - branch: {branch}\n\
             - files changed:\n{files}\n\n\
             Answer with at most {lines} plain lines of prose, no markdown, no bullet \
             characters, no commit subject, no sha or branch names. Describe the change, \
             not the process. If the files do not tell you enough, say only what they do \
             tell you.",
            node = facts.node_id,
            branch = facts.branch,
            files = facts
                .files
                .iter()
                .take(40)
                .map(|path| format!("  {path}"))
                .collect::<Vec<_>>()
                .join("\n"),
            lines = MAX_DETAIL_LINES,
        );
        let answer = self.ask(&prompt, &facts.run_id).await?;
        sanitize_detail(&answer)
    }

    /// Whether to replay the branch onto a newer commit or escalate. Any
    /// failure to get a clean answer escalates — the safe direction.
    pub async fn rebase_advice(&self, facts: &StaleBaseFacts) -> RebaseAdvice {
        let prompt = format!(
            "You are the git manager for an agent harness. A queued mutation was rejected \
             because its base is stale. Facts:\n\
             - node: {node}\n\
             - base the work was built on: {base}\n\
             - where the branch is now: {head}\n\
             - files the request touches:\n{files}\n\n\
             Reply with exactly one line, nothing else.\n\
             `REBASE <sha>` to replay the work onto that commit — the sha must be one of \
             the two above.\n\
             `ESCALATE <reason>` if replaying could lose or silently mangle work, or if \
             the two commits touch the same files.",
            node = facts.node_id,
            base = facts.base_commit,
            head = facts.head_commit,
            files = facts
                .files
                .iter()
                .take(40)
                .map(|path| format!("  {path}"))
                .collect::<Vec<_>>()
                .join("\n"),
        );
        match self.ask(&prompt, &facts.node_id).await {
            Some(answer) => parse_rebase_advice(&answer, &facts.base_commit, &facts.head_commit),
            None => RebaseAdvice::Escalate {
                reason: "advisor unavailable".to_owned(),
            },
        }
    }

    /// One turn, final text only. Mirrors the orchestrator's collection
    /// loop: `Finished` carries the answer, deltas are the fallback for a
    /// runtime that streams without a terminal payload.
    async fn ask(&self, prompt: &str, label: &str) -> Option<String> {
        let spec = SpawnSpec {
            task_id: Uuid::new_v4(),
            objective: prompt.to_owned(),
            workspace: std::env::temp_dir(),
            allowed_paths: vec![],
            forbidden_paths: vec![],
            tool_allowlist: vec![],
            tool_denylist: [
                "Bash(git commit:*)",
                "Bash(git merge:*)",
                "Bash(git rebase:*)",
                "Bash(git push:*)",
                "Bash(git reset:*)",
            ]
            .into_iter()
            .map(str::to_owned)
            .collect(),
            model: self.model.clone(),
            timeout_secs: self.timeout.as_secs(),
            isolated_home: None,
        };
        let handle =
            match tokio::time::timeout(self.timeout, self.adapter.start_session(spec)).await {
                Ok(Ok(handle)) => handle,
                Ok(Err(error)) => {
                    tracing::warn!(label, %error, "git advisor session did not start");
                    return None;
                }
                Err(_) => {
                    tracing::warn!(label, "git advisor session did not start in time");
                    return None;
                }
            };
        let mut events = handle.events();
        let mut deltas = String::new();
        let collected = tokio::time::timeout(self.timeout, async {
            loop {
                match events.recv().await {
                    Ok(AdapterEvent::TextDelta(text)) => deltas.push_str(&text),
                    Ok(AdapterEvent::Finished { final_result, .. }) => return final_result,
                    Ok(AdapterEvent::Failed(failure)) => {
                        tracing::warn!(label, %failure, "git advisor turn failed");
                        return None;
                    }
                    Ok(_) => {}
                    Err(RecvError::Lagged(skipped)) => {
                        tracing::warn!(label, skipped, "git advisor event stream lagged");
                    }
                    Err(RecvError::Closed) => return None,
                }
            }
        })
        .await;
        let text = match collected {
            Ok(Some(text)) => text,
            Ok(None) => deltas,
            Err(_) => {
                let _ = handle.cancel().await;
                tracing::warn!(label, "git advisor turn timed out");
                return None;
            }
        };
        (!text.trim().is_empty()).then_some(text)
    }
}

/// Model prose reduced to something safe to put in a commit body: control
/// characters gone, no leading bullets or `#` (which git strips as a
/// comment), bounded in lines and bytes. `None` when nothing survives.
pub fn sanitize_detail(raw: &str) -> Option<String> {
    let mut lines = Vec::new();
    for line in raw.lines() {
        let cleaned = line
            .chars()
            .filter(|c| !c.is_control())
            .collect::<String>()
            .trim()
            .trim_start_matches(['-', '*', '#', '>'])
            .trim()
            .to_owned();
        if cleaned.is_empty() {
            continue;
        }
        lines.push(cleaned);
        if lines.len() == MAX_DETAIL_LINES {
            break;
        }
    }
    let mut detail = lines.join("\n");
    if detail.len() > MAX_DETAIL_BYTES {
        // Cut on a char boundary, not a byte index into a multi-byte char.
        let end = (0..=MAX_DETAIL_BYTES)
            .rev()
            .find(|i| detail.is_char_boundary(*i))
            .unwrap_or(0);
        detail.truncate(end);
        detail = detail.trim_end().to_owned();
    }
    (!detail.is_empty()).then_some(detail)
}

/// Parse the advisor's one line. Anything unexpected escalates, and a
/// `REBASE` target that is not one of the two commits we offered is
/// treated as unexpected — the model picks between known commits, it does
/// not name new ones.
pub fn parse_rebase_advice(answer: &str, base: &str, head: &str) -> RebaseAdvice {
    let escalate = |reason: &str| RebaseAdvice::Escalate {
        reason: reason.to_owned(),
    };
    let Some(line) = answer.lines().map(str::trim).find(|l| !l.is_empty()) else {
        return escalate("advisor returned nothing");
    };
    let line = line.trim_start_matches(['`', '-', '*', ' ']).trim();
    if let Some(rest) = line.strip_prefix("REBASE") {
        let onto = rest.trim().trim_matches('`').trim();
        if !is_sha(onto) {
            return escalate("advisor named a non-sha rebase target");
        }
        // The model chooses between commits the harness already knows.
        // Prefix-matching keeps a short sha legal without letting an
        // unknown one through.
        for candidate in [base, head] {
            if candidate.starts_with(onto) || onto.starts_with(candidate) {
                return RebaseAdvice::Rebase {
                    onto: candidate.to_owned(),
                };
            }
        }
        return escalate("advisor named a commit outside this request");
    }
    if let Some(rest) = line.strip_prefix("ESCALATE") {
        let reason = rest.trim().trim_matches('`').trim();
        return escalate(if reason.is_empty() {
            "advisor escalated without a reason"
        } else {
            reason
        });
    }
    escalate("advisor answer did not parse")
}

/// A plausible abbreviated-or-full object name. Hex only, which is what
/// keeps model text out of argv even before `rev-parse` sees it.
fn is_sha(value: &str) -> bool {
    (7..=40).contains(&value.len()) && value.chars().all(|c| c.is_ascii_hexdigit())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sanitize_strips_bullets_control_chars_and_caps_length() {
        let raw = "- Adds the scanner route\r\n\n* and its styles\n#comment\n";
        assert_eq!(
            sanitize_detail(raw).expect("detail"),
            "Adds the scanner route\nand its styles\ncomment"
        );
        assert_eq!(sanitize_detail("   \n\n"), None);
        let long = "x".repeat(MAX_DETAIL_BYTES * 2);
        assert!(sanitize_detail(&long).expect("detail").len() <= MAX_DETAIL_BYTES);
        let many = (0..20).map(|i| format!("line {i}")).collect::<Vec<_>>();
        assert_eq!(
            sanitize_detail(&many.join("\n"))
                .expect("detail")
                .lines()
                .count(),
            MAX_DETAIL_LINES
        );
    }

    #[test]
    fn rebase_advice_accepts_only_the_commits_it_was_offered() {
        let base = "1111111111111111111111111111111111111111";
        let head = "2222222222222222222222222222222222222222";
        assert_eq!(
            parse_rebase_advice(&format!("REBASE {head}"), base, head),
            RebaseAdvice::Rebase {
                onto: head.to_owned()
            }
        );
        // an abbreviation of a known commit still resolves to the full one
        assert_eq!(
            parse_rebase_advice("`REBASE 2222222`", base, head),
            RebaseAdvice::Rebase {
                onto: head.to_owned()
            }
        );
        // a sha we never offered, a non-sha, and shell-ish text all escalate
        for answer in [
            "REBASE 3333333333333333333333333333333333333333",
            "REBASE --onto=evil",
            "REBASE $(rm -rf /)",
            "sure, I'll rebase it for you",
            "",
        ] {
            assert!(
                matches!(
                    parse_rebase_advice(answer, base, head),
                    RebaseAdvice::Escalate { .. }
                ),
                "{answer:?} should escalate"
            );
        }
        assert_eq!(
            parse_rebase_advice("ESCALATE both commits touch src/lib.rs", base, head),
            RebaseAdvice::Escalate {
                reason: "both commits touch src/lib.rs".to_owned()
            }
        );
    }
}
